version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blog-tech-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: blog_tech
      DB_PASSWORD: tech20262
      DB_NAME: blog_tech_2_db
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    container_name: blog-tech-db
    restart: always
    environment:
      POSTGRES_USER: blog_tech
      POSTGRES_PASSWORD: tech20262
      POSTGRES_DB: blog_tech_2_db
    ports: 
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: